# Reviewing
# Journals
- where: ACM Transactions on Software Engineering and Methodology Journal.
  kind: Review
  year: 2022
- where: Journal of Systems and Software.
  kind: Review
  year: 2021, 2022
- where: Journal of Information Security and Applications.
  kind: Review
  year: "2020, 2021"
- where: Empirical Software Engineering Journal.
  kind: Review
  year: "2019, 2020, 2021, 2022"
- where: Transactions on Software Engineering Journal.
  kind: Review
  year: "2019, 2020, 2021, 2022"
- where: Software Quality Journal.
  kind: Review
  year: "2020, 2021"
- where: Science of Computer Programming Journal.
  kind: Review
  year: 2021
- where: Journal of IEEE Software
  kind: review
  year: 2020
# Conferences
- where: International Conference on Program Comprehension (ICPC) - ERA and RENE Tracks.
  kind: ReviewConf
  year: 2023
- where: International Conference on Mining Software Repositories (MSR) - Data and Tool Showcase track.
  kind: ReviewConf
  year: 2023
- where: International Conference on Predictive Models and Data Analytics in Software Engineering (PROMISE).
  kind: ReviewConf
  year: 2022
- where: International Conference on Mining Software Repositories (MSR) - Hackathon track.
  kind: ReviewConf
  year: 2022
- where: International Conference on Open Source Systems (OSS).
  kind: ReviewConf
  year: 2022
- where: The Belgium-Netherlands Software Evolution Workshop (BENEVOL).
  year: 2022
  kind: ReviewConf
- where: International Conference on Cloud Computing and Artificial Intelligence (CloudTech). 
  kind: ReviewConf
  year: 2020
- where: International Conference on Mining Software Repositories (MSR).
  kind: ReviewConf
  sub: "Sub-review: "
  year: "2020, 2021"
- where: International Conference on Software Maintenance and Evolution (ICSME).
  kind: ReviewConf
  sub: "Sub-review: "
  year: "2020, 2021"
- where: International Conference on Software and Systems Reuse (ICSR).
  kind: ReviewConf
  sub: "Sub-review: "
  year: 2020
# Oraganization 
- event: The 4th International Workshop on Software Health in Projects, Ecosystems and Communities (SoHeal)
  where: Co-located with ICSE 2021
  kind: Organization
  link: http://soheal.github.io/
- event: ChaossCon Europ 2020
  where: Co-located with FOSDEM in Brussels
  kind: Organization
  link: https://chaoss.community/chaosscon-2020-eu/
- event: "Moroccan Collegiate Programming Contest 2014"
  where: ENSIAS, Rabat - Morocco
  kind: Organization
  link:  http://ensias.um5.ac.ma/library/journals/ideo-iusto-valde-vulpes

# Teaching Lecturer
- role: "Capita Selecta of Software Engineering"
  link: https://caliweb.vub.be/?page=course-offer&id=005049&anchor=1&target=pr&year=2324&language=en&output=html
  course: "For Master students at Vrije Universiteit Brussel, Brussels - Belgium"
  kind: Lecturer
  year: 2022/2023

- role: "Security in Computing"
  link: https://caliweb.vub.be/?page=course-offer&id=009554&anchor=1&target=pr&year=2324&language=en&output=html
  course: "For Master students at Vrije Universiteit Brussel, Brussels - Belgium"
  kind: Lecturer
  year: 2012/2023

  # Teaching Assistant
- role: "Software Architectures"
  link: https://caliweb.vub.be/?page=course-offer&id=005419&anchor=1&target=pr&year=2324&language=en&output=html
  course: "For Master students at Vrije Universiteit Brussel, Brussels - Belgium"
  prof: "With <a href=\"http://soft.vub.ac.be/~cderoove/\">Prof. Coen De Roover</a>"
  kind: Assistant
  year: 2020/2021, 2021/2022

- role: "Software Evolution"
  link: https://webcontent.umons.ac.be/web/en/pde/2019-2020/aa/S-INFO-029.htm
  course: "For Master students at Université de Mons, Mons - Belgium"
  prof: "With <a href=\"http://informatique.umons.ac.be/perso/Mens.Tom/\">Prof. Tom Mens</a>"
  kind: Assistant
  year: 2019/2020

# Supervision
- title: "Detecting Code Smells in Dockerfiles"
  student: I. Angillis
  univ: "Vrije Universiteit Brussel, Brussels - Belgium"
  prof: "Prof. Coen De Roover"
  year: "Master 2022/2023"
  kind: Supervision

- title: "An Empirical Analysis of the DockerHub Inheritance Network"
  student: J. S. Lesy
  univ: "Vrije Universiteit Brussel, Brussels - Belgium"
  prof: "Prof. Coen De Roover"
  year: "Master 2022/2023"
  kind: Supervision

- title: "Effort to Upgrade APIs with Breaking Changes in Maven Central"
  student: K. Mankevič
  univ: "Eindhoven University of Technology"
  prof: "Prof. Coen De Roover"
  year: "Master 2021/2022"
  kind: Supervision

- title: "Graph-Based Security Smell Detection For Infrastructure as Code"
  student: A. R. Van Quickelberghe
  univ: "Vrije Universiteit Brussel, Brussels - Belgium"
  prof: "Prof. Coen De Roover"
  year: "Master 2021/2022"
  kind: Supervision

- title: "On License Compatibility in Dependency Network of OSS Package Repositories"
  student: I. S. Makari
  univ: "Vrije Universiteit Brussel, Brussels - Belgium"
  prof: "Prof. Coen De Roover"
  year: "Bachelor 2020/2021"
  kind: Supervision

# Projects
- project: "SECO-ASSIST: <b style=\"font-style: italic;\">Automated Assistance for Developing Software in Ecosystems of the Future</b>"
  period: "March 2020 - ongoing"
  link: https://secoassist.github.io/
  role: Postdoc researcher
  kind: Projects

- project: "SENECA: <b style=\"font-style: italic;\">Software Engineering in Enterprise Cloud Applications</b>"
  period: "September 2017 - December 2018"
  link: http://senecaproject.github.io/
  role: PhD student
  kind: Projects

- project: "DISSE: <b style=\"font-style: italic;\">Data-Intensive Software System Evolution</b>"
  period: "June 2016 - June 2017"
  link: https://www.researchgate.net/project/DISSE-Data-Intensive-Software-System-Evolution
  role: PhD student
  kind: Projects

# Awards
- award: "IEEE Computer Society TCSE Best Paper Award"
  where: "SANER 2019, Hangzhou - China"
  link: "assets/other/best_paper_saner.pdf"
  kind: Awards
