- where: Journal of Information Security and Applications.
  kind: Review
  year: 2020
- where: Empirical Software Engineering Journal.
  kind: Review
  year: "2019, 2020"
- where: Transactions on Software Engineering Journal.
  kind: Review
  year: "2019, 2020"
- where: Software Quality Journal.
  kind: Review
  year: 2020
- where: International Conference on Cloud Computing and Artificial Intelligence.
  kind: Review
  year: 2020
- where: Mining Software Repositories.
  kind: Review
  sub: "Sub-review: "
  year: 2020
- where: International Conference on Software Maintenance and Evolution.
  kind: Review
  sub: "Sub-review: "
  year: 2020
- where: International Conference on Software and Systems Reuse.
  kind: Review
  sub: "Sub-review: "
  year: 2020